name: Deploy to dev environment

on:
  push:
    branches:
      - develop
  workflow_dispatch:

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    environment: dev
    steps:

      - uses: actions/checkout@master

      - uses: actions/setup-dotnet@v1
        name: Set dotnet version
        with:
          dotnet-version: '5.0.x'

      - run: dotnet restore
        name: Restore nuget packages

      - run: dotnet build --configuration Release
        name: build

      - run: dotnet publish -c Release -o ./demobc
        name: publish
        
      - name: login 
        uses: azure/login@v1
        with:
          creds: ${{ secrets.CREDENTIALS }}

      - name: 'Deploy to dev environment'
        uses: azure/webapps-deploy@v2
        with:
          app-name: demobc          
          package: './demobc'
