name: PR

on:
  pull_request:
    branches: [ develop ]
  workflow_dispatch:

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - uses: actions/setup-dotnet@v1
        name: Set dotnet version
        with:
          dotnet-version: '5.0.x'

      - run: dotnet restore
        name: Restore nuget packages

      - run: dotnet build --no-restore
        name: build

      - run: dotnet test --no-build --verbosity nomal